from fastapi import APIRouter, Depends

from app.api.deps import get_current_user

router = APIRouter(prefix="/dns-wizard", tags=["dns-wizard"])


def _records(domain: str, hostname: str, server_ip: str) -> list[dict]:
    return [
        {
            "type": "MX",
            "name": f"{domain}.",
            "value": f"10 {hostname}.",
            "ttl": 3600,
            "description": "Mail exchanger – routes email to your mail server",
        },
        {
            "type": "A",
            "name": f"{hostname}.",
            "value": server_ip or "<your-server-ip>",
            "ttl": 3600,
            "description": "IP address of your mail server",
        },
        {
            "type": "TXT",
            "name": f"{domain}.",
            "value": f"v=spf1 mx ~all",
            "ttl": 3600,
            "description": "SPF record – authorises your mail server to send email for this domain",
        },
        {
            "type": "TXT",
            "name": f"_dmarc.{domain}.",
            "value": f"v=DMARC1; p=none; rua=mailto:dmarc-reports@{domain}",
            "ttl": 3600,
            "description": "DMARC policy – set p=quarantine or p=reject once SPF/DKIM are verified",
        },
        {
            "type": "TXT",
            "name": f"mail._domainkey.{domain}.",
            "value": "<paste DKIM public key from /tmp/docker-mailserver/opendkim/keys/domain.tld/mail.txt>",
            "ttl": 3600,
            "description": "DKIM public key – generated by docker-mailserver setup; run: docker exec mail-server setup config dkim",
        },
        {
            "type": "PTR",
            "name": f"{server_ip or '<your-server-ip>'}",
            "value": f"{hostname}.",
            "ttl": 3600,
            "description": "Reverse DNS (rDNS/PTR) – must be set with your hosting provider",
        },
        {
            "type": "TXT",
            "name": f"_mta-sts.{domain}.",
            "value": f"v=STSv1; id={domain.replace('.', '')}",
            "ttl": 3600,
            "description": "MTA-STS version identifier – update the id value whenever you change your MTA-STS policy",
        },
        {
            "type": "TXT",
            "name": f"_smtp._tls.{domain}.",
            "value": "v=TLSRPTv1; rua=mailto:tls-reports@" + domain,
            "ttl": 3600,
            "description": "TLS reporting – receive TLS failure reports (optional)",
        },
    ]


@router.get("/{domain}")
def dns_wizard(
    domain: str,
    hostname: str = "",
    server_ip: str = "",
    _=Depends(get_current_user),
):
    effective_hostname = hostname or f"mail.{domain}"
    return {
        "domain": domain,
        "hostname": effective_hostname,
        "server_ip": server_ip,
        "records": _records(domain, effective_hostname, server_ip),
    }
